### PR TITLE
add the ability to expand thumbnails programmatically

### PR DESCRIPTION
**Pull request by mkchoi212**
I've made a simple change to enable the thumbnail to be expanded programmatically.
All I've done is to make the expand function public.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR :sparkles:. How about exposing collapse while you're at it?

**Comment by mkchoi212** [comment]
Just did!

**Comment by jpsim** [comment]
Finally, I'd rather the demo didn't do this automatically. So please just keep the changes in `JPSThumbnailAnnotationView.h`. Thanks!

**Comment by mkchoi212** [comment]
please merge this PR! Thanks!

**Comment by jpsim** [comment]
I didn't get notified when you pushed your last commit, so I just saw this now. Thanks!

**Pull request merged**
